### ISSUE TITLE
AttributeError: 'ValueMapTool' object has no attribute 'moved'

### ISSUE THREAD

**Issue by pigreco** [jorgealmerio/valuetool#1]
I installed the plugin but as soon as I try to use it (which I have been doing for a long time in version 2.x) this error appears immediately:
![image](https://user-images.githubusercontent.com/7631137/39404380-6f04f56a-4b92-11e8-92f6-d94f36b0b7da.png)

OSGEo4W64 - win 10 64b
QGIS 3.0.2 Girona [307d082e3d](https://github.com/qgis/QGIS/commit/307d082e3d)

**Comment by jorgealmerio** [comment]
Bug fixed on version 3.0.1, Please update it!
Sorry about this.
