### ISSUE TITLE
Error: ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by cesarcorreo** [jorgealmerio/valuetool#16]
Dear Jorge,
First, thanks for your pluging.
I have just update QGIS to 3.20. 
From that moment I have the following error (The error only happens with Google earth, OSM or similar layers not with raster layers created by me from interpolations):
_ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "C:\Users/TYPSA/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\valuetool\valuewidget.py", line 432, in printValue
    rowCol = self.getRowCol(layer, pos)
  File "C:\Users/TYPSA/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\valuetool\valuewidget.py", line 303, in getRowCol
    xres = extent.width() / layer.dataProvider().xSize()
ZeroDivisionError: float division by zero

Versión de Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May 3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
Versión de QGIS: 3.20.0-Odense Odense, decaadbb31

Ruta de Python:
C:/PROGRA~1/QGIS32~1.0/apps/qgis/./python
C:/Users/TYPSA/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/TYPSA/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.0/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.20.0\bin\python39.zip
C:\PROGRA~1\QGIS32~1.0\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib
C:\Program Files\QGIS 3.20.0\bin
C:\PROGRA~1\QGIS32~1.0\apps\Python39
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages\Pythonwin
C:/Users/TYPSA/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\TYPSA\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
C:\Users/TYPSA/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web
C:\Users\TYPSA\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins_

In the Spanish telegram group unless other uses have the same problem.

Thanks

**Comment by jorgealmerio** [comment]
Solved on June 30!
