### ISSUE TITLE
Does not load the layers

### ISSUE THREAD

**Issue by bellanz80** [jorgealmerio/valuetool#2]
Hi. In the "Table" panel, the project layers are not loaded. And although I change the option of "visible layers" or "selected layers", no layer is loaded or displayed.
Thank you
QGIS 3.2.3
windows 64 bit, 1803, compilation 17134.286

Luca Bellani

![1](https://user-images.githubusercontent.com/38449926/45961570-70c1d500-bfe4-11e8-9f76-a4ff60284253.PNG)
![2](https://user-images.githubusercontent.com/38449926/45961571-70c1d500-bfe4-11e8-8aa4-ed16905371cd.PNG)
![3](https://user-images.githubusercontent.com/38449926/45961573-70c1d500-bfe4-11e8-8288-22c2dbf78763.PNG)

**Comment by jorgealmerio** [comment]
You are right, the "Selected layers" and "All layers" options are not working!!

But "Visible layers" options worked for me on Qgis 3.2.2. 
Could please enable the layer "HILLSHADE MDS" of your project and let me know if it works with "Visible layers" option?

By the way, remember that this plugin can not read Google Satellite values or from others WMS services too.

I will try to fix this bug soon!

Thank you

**Comment by bellanz80** [comment]
Hello, in the project I have dozens of layers. But the only one that I'm interested in monitoring with the Value tool is the DEM. It's a layer that I do not see on the canvas.
In QGIS 2.18.24 I have no problem.
Thank you very much for the quick answer!

**Comment by bellanz80** [comment]
Hi. The problem is also presented in QGIS 3.4.5 LTR, and 3.6. With installation of a new clean profile, without any other plug in installed.
Windows 10 64 bit, v.1809
Thanks for the support.

**Comment by jorgealmerio** [comment]
Could you please send me this layer or part of it (you can use Raster\Extraction\Clip Raster by Extent)?

**Comment by bellanz80** [comment]
Hi, Annex a cut of one of the digital terrain models.
Thank you very much for the courtesy.
[value_tool.zip](https://github.com/jorgealmerio/valuetool/files/3004087/value_tool.zip)

**Comment by jorgealmerio** [comment]
I launched a new Value tool version 3.0.2 today that must fix this bug, please update it and let me know if it solved!

**Comment by bellanz80** [comment]
yes!!! it works perfectly !! Thank you very much, what a great job.
