### ISSUE TITLE
May display wrong value for F64, UInt32 and Int32

### ISSUE THREAD

**Issue by jfbourdon** [jorgealmerio/valuetool#20]
PR #15 changed the function used to retrieve values from the QgsRasterDataProvider which may return wrong values when exceeding the `F32` range. [More details in this issue here](https://github.com/qgis/QGIS/issues/44902).

**Comment by jfbourdon** [comment]
Now resolved in QGIS 3.22.

**Comment by jorgealmerio** [comment]
Very Good!
