### ISSUE TITLE
Feature request: add support for PostGIS raster layers

### ISSUE THREAD

**Issue by effjot** [jorgealmerio/valuetool#26]
Is it possible to add PostGIS raster support?
When I remove the test `ayer.providerType() in == "gdal"` from valuewidget.py line 260, it seems to work with PostGIS layers, too.
Are there any issues/limitation that I’m not aware of?
If not, I could prepare a PR.

Thanks!
Florian

**Comment by jorgealmerio** [comment]
I really don't know, can you make the tests? I can not work on it these days.

**Comment by effjot** [comment]
So far, it seems to work. We’ll put it throught its paces and I hope I can prepare a PR next week.
