### ISSUE TITLE
Feature request: Add support for QGSMeshLayer Type (QGIS > 3.6)

### ISSUE THREAD

**Issue by ZedeN1** [jorgealmerio/valuetool#3]
Would be great if value tool worked with QGIS Mesh type layers. Similar to Profile Tool changes added in 4.1.6

**Comment by jorgealmerio** [comment]
Done ! 
If you like consider make a small donation, any value. Thanks!
 
[DONATE](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=G5ERSTGG4U426&item_name=Value+tool&currency_code=BRL&source=url)

**Comment by AlisterH** [comment]
Well, partially implemented :)  

Load the test file from #7 into QGIS and you'll see that it has multiple datasets which can be symbolised.  If you use the Profile Tool plugin, you'll see that when you add the layer to the profile it will plot the same dataset that is symbolised in the map.  Likewise the identify tool will provide the value of the same dataset that is symbolised on the map.  But it seems the Value Tool always just displays the value of the "Bed elevation" dataset, regardless of which dataset is symbolised in the map.

I don't have any other formats to test with to see if this is only a limitation with HEC-RAS mesh layers.

**Comment by jorgealmerio** [comment]
You are right! For while Value tool only get bed elevation values! In the future I intend to add this feature.
It's a limitation of the Value tool plugin for now.

**Comment by ZedeN1** [comment]
> [DONATE](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=G5ERSTGG4U426&item_name=Value+tool&currency_code=BRL&source=url)

Done !

> You are right! For while Value tool only get bed elevation values! In the future I intend to add this feature.
> It's a limitation of the Value tool plugin for now.

Would love to get this added in future update! 😊

**Comment by jorgealmerio** [comment]
Ok, thanks for the donation! I will try to implement it as soon as possible.

**Comment by jorgealmerio** [comment]
> 
> 
> Well, partially implemented :)
> 
> Load the test file from #7 into QGIS and you'll see that it has multiple datasets which can be symbolised. If you use the Profile Tool plugin, you'll see that when you add the layer to the profile it will plot the same dataset that is symbolised in the map. Likewise the identify tool will provide the value of the same dataset that is symbolised on the map. But it seems the Value Tool always just displays the value of the "Bed elevation" dataset, regardless of which dataset is symbolised in the map.
> 
> I don't have any other formats to test with to see if this is only a limitation with HEC-RAS mesh layers.

Done!
Please check it on version 3.0.8

**Comment by ZedeN1** [comment]
Thank you! Works exactly as I hoped!
