### ISSUE TITLE
Added height from DTM to coordinate string

### ISSUE THREAD

**Issue by mwindowshz** [jorgealmerio/valuetool#5]
HI
I was searching for a tool to see elevation data from DEM / DTM file.

Found your ValueTool
had a problem that the prining of the value was according to the loaded raster, and if my DTM is composed of several files, I cannot hover mouse and see the hight, it every time prints in diffrent line in the table and some are hidden.

wrote a solution, I am not sure the code is nice, but it works well.
now I can load DTM,, or orthphoto and DTM, and hover with mouse over them and get coordinate and height.

![image](https://user-images.githubusercontent.com/17617515/82607845-46ae2500-9bc2-11ea-868e-111d5b1ad48d.png)

I added these lines:
![image](https://user-images.githubusercontent.com/17617515/82608008-9391fb80-9bc2-11ea-8e2a-96fc7b7416fb.png)

I am going to try to do a pull request as well.

Thanks for your great tool.
This is such a basic function missing from QGIS, to display full coordinate and height.

M.

```
ident = layer.dataProvider().identify(pos, QgsRaster.IdentifyFormatValue, canvas.extent(), width, height ).results()

                  #   test add DEM value to have coordinate and height
                  if ident is not None:
                    if len(ident) == 1:
                        try:
                            self.labelStatus.setText(self.tr('Coordinate:') + ' (%f, %f,%f)' % (position.x(), position.y(),ident.get(1)))
                        except:
                            t = 100
```

**Comment by jorgealmerio** [comment]
Hi, I did your suggestion!
But I could not made it to work using your Pull request.
I Inserted 1 code line at 379:

`# mwindowshz Pull Request
self.labelStatus.setText(self.tr('Coordinate:') + '{},{},{}'.format(position.x(), position.y(),bandvalue))`

I hope you don't mind!
