### ISSUE TITLE
Add row and column position

### ISSUE THREAD

**Issue by jfbourdon** [jorgealmerio/valuetool#8]
Currently, the coordinate of the cursor' position is shown at the bottom of the widget, but it could be useful to also have displayed the row and column position inside each raster. I could see two more colums at the right of the column Value. They could be displayed only as an option.

If needed, the second block of code in [this question on GIS StackExchange](https://gis.stackexchange.com/a/261538/109610) print the row and column of the active raster to the Python console.

I would agree that usually only georeferenced coordinates are relevant in GIS, but I was trying to link a specific pixel in QGIS to the same raster inside a numpy array... and I was too leasy to calculate myself the position by using the CRS and transform metadata.

**Comment by jorgealmerio** [comment]
Done by yourself!
Thanks!
